### ISSUE TITLE
No way for base template to know the current page?

### ISSUE THREAD

**Issue by smth** [datopian/frontend-v2#10]
It would be good to be able to style the current page link differently in the main navigation. Perhaps by querying the current path? {% if current_slug == "about" %}.

**Comment by anuveyatsu** [comment]
@smth yes, we need to pass some parameter from controller, e.g., I'm doing so in orgs and collections page: https://github.com/datopian/frontend-v2/blob/master/routes/dms.js#L89

**Comment by anuveyatsu** [comment]
Closing this as FIXED. See comment above.
