### ISSUE TITLE
q param in `package_search`

### ISSUE THREAD

**Issue by EvgeniiaVak** [datopian/frontend-v2#148]
https://github.com/datopian/frontend-v2/blob/235944eeb49156b97d23ff3699af69e5ee218028/lib/dms.js#L18-L22

Are we sure we need all params in the body? 
For example `q` should be in the URL according to the [CKAN doc](https://docs.ckan.org/en/latest/api/index.html): http://demo.ckan.org/api/3/action/package_search?q=spending.

I also tried POST http://demo.ckan.org/api/3/action/package_search with 
```
{
	"q": "name:sales_data"
}
```
in the body - does not filter anything, but http://demo.ckan.org/api/3/action/package_search?q=name:sales_data shows only the required result.

**Comment by anuveyatsu** [comment]
@EvgeniiaVak do you mean that it works with GET requests but not with POST?

**Comment by EvgeniiaVak** [comment]
@anuveyatsu 
not exactly, http://demo.ckan.org/api/3/action/package_search?q=name:sales_data - works regardless of whether it is GET or POST.
but when `q` is in the body of the request (which the code snippet does - puts it in the body), it doesn't work

**Comment by anuveyatsu** [comment]
@EvgeniiaVak probably curl command is wrong:

```
curl -XPOST -H "Content-type: application/json" -d '{"q":"name:sales_data"}' 'https://demo.ckan.io/api/3/action/package_search'
```

**Comment by EvgeniiaVak** [comment]
@anuveyatsu the curl code was from postman app. It's strange the one you've sent doesn't work for me (in terminal) at all:
```
curl: (6) Could not resolve host: demo.ckan.io
```

but anyways, I now tried a quick test it in JS:
```
const fetch = require('node-fetch')

fetch('http://demo.ckan.org/api/3/action/package_search', {
  method: 'POST',
  body: JSON.stringify({"q":"name:sales_data"}),
  headers: { 'Content-Type': 'application/json' }
}).then( response => {
  response.json().then(
    respBody => console.log('Found results with {"q":"name:sales_data"} in request body:', respBody.result.count)
  )
})


fetch('http://demo.ckan.org/api/3/action/package_search?q=name:sales_data', {
  method: 'POST',
  body: JSON.stringify({}),
  headers: { 'Content-Type': 'application/json' }
}).then( response => {
  response.json().then(
    respBody => console.log('Found results with q=name:sales_data in URL:', respBody.result.count)
  )
})
```

The output is:
```
Found results with q=name:sales_data in URL: 1
Found results with {"q":"name:sales_data"} in request body: 484
```

which means that this filter doesn't work when in the request body.

I suggest we add another parameter to the [frontend-v2 search function](https://github.com/datopian/frontend-v2/blob/235944eeb49156b97d23ff3699af69e5ee218028/lib/dms.js#L13) (`params` for example) so that we could specify both query and URL params if needed.

**Comment by anuveyatsu** [comment]
@EvgeniiaVak sorry, I had wrong url in the curl command. Fixed now.

I'm also using an app similar to postman and it works just fine.

**Comment by anuveyatsu** [comment]
@EvgeniiaVak could you check if this curl command works and if so please close this issue:

```
curl -XPOST -H "Content-type: application/json" -d '{"q":"name:sales_data"}' 'https://demo.ckan.org/api/3/action/package_search'
```

**Comment by EvgeniiaVak** [comment]
@anuveyatsu the curl command you've sent works all right
