### ISSUE TITLE
`v1.0.x` branch and the project versioning

### ISSUE THREAD

**Issue by EvgeniiaVak** [datopian/frontend-v2#165]
There are some features in `v1.0.x` branch which probably can be in master (almost everything - see the comparison https://github.com/datopian/frontend-v2/compare/v1.0.x - except the version number update).

And in general something strange is going on with the project versions: v1.1.0 comes before v1.0.1.

Some themes depend on the changes from `v1.0.x` branch and if we wish to update it to use new frontend-v2, we need to have them in the master branch too.

What to do?
- create a PR from `v1.0.x` branch to `master`
- do nothing with frontend-v2 - we shouldn't merge them for some reason, update the theme instead.

**Comment by anuveyatsu** [comment]
@EvgeniiaVak creating PR from `v1.0.x` to `master` sounds reasonable.

The reason that v1.0.1 was released after v1.1.0 is that they were in different branches. So we are doing work on `v1.0.x` independently and releasing tags.

**Comment by EvgeniiaVak** [comment]
@anuveyatsu 
Is it ok if I merge `master` into `v1.0.x` to resolve conflicts?

**Comment by anuveyatsu** [comment]
@EvgeniiaVak yes, option 2 sounds ok to me too.

**Comment by EvgeniiaVak** [comment]
FIXED. See https://github.com/datopian/frontend-v2/commit/e9df25e6c5cd2fa3eaeab072cdce10b569a02776
