### ISSUE TITLE
Erroneous em tag

### ISSUE THREAD

**Issue by smth** [datopian/frontend-v2#20]
The layout on this page https://frontend-v2-openddk.herokuapp.com/news is a bit broken, looks like the second column has gotten wrapped in an `em` tag somehow. I couldn't reproduce locally.

**Comment by anuveyatsu** [comment]
@smth I can reproduce locally but I don't understand how it gets wrapped in an `em`. Is it something to do with Tailwind?

**Comment by smth** [comment]
I wouldn't have thought so. Maybe an unclosed tag in the data somewhere? Assuming you are using a different API, that would explain why you are seeing it, while I'm not.

**Comment by anuveyatsu** [comment]
This was happening due to content in one of the posts from WP...

**Comment by anuveyatsu** [comment]
FIXED now http://opendata.dk/blog
