### ISSUE TITLE
Org collections image bg colour

### ISSUE THREAD

**Issue by smth** [datopian/frontend-v2#21]
The background colour for the images here https://frontend-v2-openddk.herokuapp.com/organization should probably be changed to white. As this page is sharing a template with groups, there's a decision to be made about how to achieve this. Perhaps an "if orgs" statement in the template.

The change that needs to be made is changing `bg-secondary` to `bg-white` here https://github.com/datopian/frontend-v2/blob/master/themes/opendk/views/collections-home.html#L33

**Comment by anuveyatsu** [comment]
FIXED
