### ISSUE TITLE
Cannot set config value on instantiated app

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/frontend-v2#29]
## Description
As a developer I want to be able to set config values on the fly so that I can write robust tests that test behavior with different configurations

https://gist.github.com/starsinmypockets/f3ac2746c3f4725249e3311e5372678b

## Acceptance Criteria
- [ ] Tests in gist (or similar) pass

## Tasks
- [ ] Analyze / update config module

**Comment by anuveyatsu** [comment]
Not sure if it worth to do...

**Comment by starsinmypockets** [comment]
It would be awesome to be able to test the app in multiple configurations to ensure that we don't cause regressions. 

I think the point of ngconf is to manage config for multiple environments.

**Comment by starsinmypockets** [comment]
Anyway this is a bug report `config.set` does not work

**Comment by starsinmypockets** [comment]
@anuveyatsu Still stuck on this unfortunately. 
 I need to be able to test how the app behaves with user-defined env variables that are not present in CI, hence: need to set env variables inside of tests
I think there might be a simple workaround here but I'm stuck :(

**Comment by anuveyatsu** [comment]
@starsinmypockets sorry but I don't think it worth to do and I would suggest not spending any time on this issue.

**Comment by starsinmypockets** [comment]
@anuveyatsu I think you misunderstand. This is a blocker for including tests of the extension work.

**Comment by starsinmypockets** [comment]
using `nconf.use('memory')` in config/index.js solves this issue
