### ISSUE TITLE
Where do we store config files, setup scripts and additional NPM packages for theming?

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-v2#4]
At the moment, I'm not sure what to do with `tailwind.config.js`, `gulpfile.js`, `/src/*` files and additional NPM packages are needed for theming of OpenDK (see `/themes/opendk/`). Probably they should be placed somewhere in the themes directory.

**Comment by smth** [comment]
Might make sense to (eventually) treat the theme as its own project, and include as a submodule. Then all this stuff could live at the root of that project.

**Comment by anuveyatsu** [comment]
@smth yes, I agree and support that option. Developers want to be able to pull new commits in this repo, e.g., bug fixes and improvements.

**Comment by anuveyatsu** [comment]
Closing as FIXED. All theme related configs etc should be stored in the project's directory. See example: https://github.com/datopian/frontend-oddk
