### ISSUE TITLE
Template changes not being automatically loaded

### ISSUE THREAD

**Issue by georgiana-b** [datopian/frontend-v2#46]
Hello! I was just following the tutorial [here](https://kb.datopian.com/#ckan-next-gen-documentation). I installed the app following [these steps](https://kb.datopian.com/#installation) using `npm`.

The server is running with no errors, everything seems to be ok but the changes I make to my custom template in `/themes/example/views/home.html` are not picked up automatically. They are picked up only after server restart, which is not triggered automatically after I change something in the template.

I also tried running the app with `nodemon`:

```
> frontend-v2@1.0.0 start /Users/g/Datopian/frontend-v2
> nodemon index.js

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
express-session deprecated undefined resave option; provide resave option index.js:51:11
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option index.js:51:11
Loading configured plugins...
example
wp
Loading configured theme...
example
Listening on :4000
``` 

Yet my changes to the theme don't trigger a restart. If I type `rs` to manually trigger it then they are loaded otherwise I'm just being served the old version of the template.

I also tried watching that folder specifically with `nodemon --watch themes index.js` and I got the same behaviour.

Does anybody else have this issue? Am I missing some configuration?

I'm running:
Node v8.16.0
macOS 10.14.6

**Comment by anuveyatsu** [comment]
@georgiana-b thanks for reporting this :+1:

I guess nodemon doesn't listen for HTML changes so you need to explicitly flag it:

```
nodemon -e "js html" index.js
```

Read more here - https://github.com/remy/nodemon#specifying-extension-watch-list

**Comment by anuveyatsu** [comment]
It isn't mentioned in the tutorial but in the README of this repo.

**Comment by georgiana-b** [comment]
Oh, thanks a lot. I was looking at the [`nodemon` docs on npm](https://www.npmjs.com/package/nodemon) which don't mention that part.

I think it would be very helpful if we would add it as a command in  `package.json`

```json
  "scripts": {
    "start": "node index.js",
    "dev": "nodemon -e 'js html' index.js"
  }
```

And then in the tutorial we could instruct people to run `npm run dev` instead of `npm start`.  This way we can avoid confusion for people who follow the tutorial while also having the freedom to change the command and arguments we use in development. 
WDYT

**Comment by georgiana-b** [comment]
Another colleague just went through this and he also instinctively tried to run `npm run dev` (i.e. `yarn dev`) which is (at least the unofficial) community practice. Will come back with a PR :)

**Comment by anuveyatsu** [comment]
Great!

**Comment by georgiana-b** [comment]
Hey, turns out I don't have permissions to push a branch and open a PR. Could you please add me as contributor?

**Comment by anuveyatsu** [comment]
@georgiana-b sorry about that - just given you permission

**Comment by anuveyatsu** [comment]
FIXED, devs can now run the dev mode by `yarn dev` or `npm run dev`. See PR above for details.
