### ISSUE TITLE
Error 409 conflict

### ISSUE THREAD

**Issue by cbenz** [datopian/frontend-v2#49]
Steps to reproduce:
- install following http://kb.datopian.com/#installation (using `API_URL=http://demo.ckan.org/api/3/action/`)
- start with `yarn start`
- go to http://localhost:4000/dataset/app-developers-toronto

There is a 409 Conflict error, and the layout is broken:

![image](https://user-images.githubusercontent.com/12686/62956319-0760d580-bdf3-11e9-8847-2fc0a96c9835.png)

Nothing is displayed in the console:

```
$ yarn start  
yarn run v1.17.3
$ node index.js
express-session deprecated undefined resave option; provide resave option index.js:51:11
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option index.js:51:11
Loading configured theme...
example
Loading configured plugins...
Listening on :4000
```

**Comment by anuveyatsu** [comment]
@cbenz looks like API endpoint isn't correct. I think demo ckan has some redirection setup. Can you try to use https protocol?

**Comment by cbenz** [comment]
It works using https, thanks!

**Comment by cbenz** [comment]
Related merge request: https://gitlab.com/datopian/tech/kb/merge_requests/4
