### ISSUE TITLE
Session lost in dev mode on code reload

### ISSUE THREAD

**Issue by cbenz** [datopian/frontend-v2#69]
In dev mode (`npm run dev`) each time the code reloads, the session is lost (i.e. if I was logged-in before, I'm logged out after code reload).

This breaks developement experience and is easily fixable by using https://www.npmjs.com/package/session-file-store

**Comment by cbenz** [comment]
Actually this should be enabled only for development mode

**Comment by rufuspollock** [comment]
WONTFIX. Not worth it at this point with portal.js
