### ISSUE TITLE
Showcase page with CKAN backend

### ISSUE THREAD

**Issue by rufuspollock** [datopian/frontend-v2#8]
## Tasks

* [x] Have it working (with DataHub style)
* [x] Have it working (with new tailwind ...)

### Outstanding issues

* `schema` for tabular data is usually missed in CKAN. We have to generate it since showcasing uses it. This creates another complication: to generate `schema` we need to read/open a resource. If it is a datastore dump, a) it might be a huge file; b) it can be "bad" data, eg, not consistent line terminators (however this happened only in 1 case)
    * => handle that case in frontend template ...
      * "is_tabular_data_package" => if false
* Large datastore dumps can crash a browser. We need to think of "preview" versions of the data, eg, query `datastore_search` for first 1k rows and compile it into data package as inlined data.
  * How about exporting data packages in the future? Eg, we need to handle `/org/name/datapackage.json` route.

**Comment by anuveyatsu** [comment]
FIXED, see the demo https://frontend-v2-openddk.herokuapp.com/city-of-copenhagen/afmaerkning_total
