### ISSUE TITLE
Template Variables - where / what / how

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/frontend-v2#9]
I want to be able to provide template variables to my custom templates.
1. What, if any, variables are available within templates by default?
1a. What is the best extant way to debug available template variables 
2. Where / how can I add custom (controller) logic to pass new variables to my theme templates?
2a. I want to implement a feature similar to https://github.com/OpenGov-OpenData/ckanext-cob_theme/blob/master/ckanext/cob_theme/templates/home/snippets/popular_datasets.html
3. Can we add this to the docs?

**Comment by anuveyatsu** [comment]
@starsinmypockets may be it's time to create a separate docs directory or repo but for now, I'll add it in the README.md of this repo.

**Comment by anuveyatsu** [comment]
FIXED, see "Theming" section of the README:

https://github.com/datopian/frontend-v2#theming

**Comment by anuveyatsu** [comment]
@starsinmypockets if you need any additional stuff in the templates, please, open a new issue with details. Thank you!
