### ISSUE TITLE
extending core controller on theme and plugin controller. 

### ISSUE THREAD

**Issue by sagargg** [datopian/frontend-v2#93]
While some changes and modification required on the core controller eg.  `changing the object key or reassign value etc.. ` could not do without overriding the entire controller on a theme or on the plugin.  

## Analysis 
 It can be fixed with the following flow. But need more analysis before implementation.

*PSUEDOCODE*
```javascript

CORE -> app.get('/', (req, res,next) =>{  
  // core controller 
  // template obj init  
   res.temObj= {}
  next()
})
PLUGIN -> app.get('/', (req, res,next) => {  
  // MIDDLE WARE CONTROLLER 
  Object.assign( res.temObj, {}) // template obj extend
  next()
})
THEME -> app.get('/', (req, res,next) => {  
  // MIDDLE WARE CONTROLLER 
  Object.assign( res.temObj, {}) // template obj extend
  next()
})
CORE -> app.get('/', (req, res,next) =>{  
    let renderobj =res.temObj
    // unset  temObj may required 
     res.render('tempate.html', {
       renderobj
      })
  })
})

**Comment by anuveyatsu** [comment]
*Copying my comment from gitlab*

What we could do here is to use `app.param` of expressJS that solves this issue:

```javascript
// this is in your theme

app.param('dataset', function (req, res, next, id) {
  console.log('CALLED')
  next()
})


// following is in core code

app.get('/collections/:name', function (req, res, next) {
  ...
})

app.get('/:owner/:dataset', function (req, res) {
  ...
})
```

So when you hit `/foo/bar` it would print `CALLED` but not when you hit `/collections/environment`.

Docs in expressjs - https://expressjs.com/en/api.html#app.param

**Comment by anuveyatsu** [comment]
Closing as FIXED as the workaround is provided.
